### ISSUE TITLE
pinout uncertainty

### ISSUE THREAD

**Issue by jonahh1** [byteduck/Arduino-VGA#1]
Ive been looking online for a pin-out diagram for where the wires need to plug into the VGA cable and was wondering if this is correct:

![](https://www.epanorama.net/faq/vga2rgb/vga2bnc.gif)

thank you.

**Comment by byteduck** [comment]
To be honest, it's been a while since I did this - so I'm not entirely sure. And unfortunately, I don't have my Arduino at the moment. I would recommend checking my https://github.com/byteduck/Arduventure repository - looks like it has some more details about pinout.

**Comment by byteduck** [comment]
Looking at `Arduventure.h`, it looks like I used two pins on the arduino hooked up to a resistor ladder for each color channel for a total of 8 possible colors. I unfortunately don't have the exact diagrams or anything anymore, as this was for a school assignment a while back. Either way - I would assume you'd hook the R,G, and B pins on the arduino to the respective pins on the VGA cable as shown in that diagram, and the same for VSYNC, HSYNC, and ground. You'll also need to make sure you're using the correct resistors for each pin to make sure you're feeding the right voltage in (I'm not sure what that would be, but a quick search will probably find what you need.) Unfortunately, I probably can't be much more help than that, since I don't have any of the materials or diagrams I used for this project anymore.

**Comment by jonahh1** [comment]
thank you so much, its great to hear I'm on the right track.
